/*
 * This file is generated by jOOQ.
 */
package io.github.pvkvetkin.scrapper.domain.jooq.tables;


import io.github.pvkvetkin.scrapper.domain.jooq.DefaultSchema;
import io.github.pvkvetkin.scrapper.domain.jooq.Keys;
import io.github.pvkvetkin.scrapper.domain.jooq.tables.records.GithubLinkRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GithubLink extends TableImpl<GithubLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_LINK</code>
     */
    public static final GithubLink GITHUB_LINK = new GithubLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubLinkRecord> getRecordType() {
        return GithubLinkRecord.class;
    }

    /**
     * The column <code>GITHUB_LINK.LINK_ID</code>.
     */
    public final TableField<GithubLinkRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>GITHUB_LINK.LAST_COMMIT_AT</code>.
     */
    public final TableField<GithubLinkRecord, OffsetDateTime> LAST_COMMIT_AT = createField(DSL.name("LAST_COMMIT_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>GITHUB_LINK.ISSUES_COUNT</code>.
     */
    public final TableField<GithubLinkRecord, Integer> ISSUES_COUNT = createField(DSL.name("ISSUES_COUNT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GITHUB_LINK.UPDATED_AT</code>.
     */
    public final TableField<GithubLinkRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private GithubLink(Name alias, Table<GithubLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private GithubLink(Name alias, Table<GithubLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GITHUB_LINK</code> table reference
     */
    public GithubLink(String alias) {
        this(DSL.name(alias), GITHUB_LINK);
    }

    /**
     * Create an aliased <code>GITHUB_LINK</code> table reference
     */
    public GithubLink(Name alias) {
        this(alias, GITHUB_LINK);
    }

    /**
     * Create a <code>GITHUB_LINK</code> table reference
     */
    public GithubLink() {
        this(DSL.name("GITHUB_LINK"), null);
    }

    public <O extends Record> GithubLink(Table<O> child, ForeignKey<O, GithubLinkRecord> key) {
        super(child, key, GITHUB_LINK);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<UniqueKey<GithubLinkRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_D);
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D8);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_D8);

        return _link;
    }

    @Override
    @NotNull
    public GithubLink as(String alias) {
        return new GithubLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubLink as(Name alias) {
        return new GithubLink(alias, this);
    }

    @Override
    @NotNull
    public GithubLink as(Table<?> alias) {
        return new GithubLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLink rename(String name) {
        return new GithubLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLink rename(Name name) {
        return new GithubLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLink rename(Table<?> name) {
        return new GithubLink(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, OffsetDateTime, Integer, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super OffsetDateTime, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super OffsetDateTime, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
