/*
 * This file is generated by jOOQ.
 */
package io.github.pvkvetkin.scrapper.domain.jooq.tables;


import io.github.pvkvetkin.scrapper.domain.jooq.DefaultSchema;
import io.github.pvkvetkin.scrapper.domain.jooq.Keys;
import io.github.pvkvetkin.scrapper.domain.jooq.tables.records.StackoverflowLinkRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StackoverflowLink extends TableImpl<StackoverflowLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STACKOVERFLOW_LINK</code>
     */
    public static final StackoverflowLink STACKOVERFLOW_LINK = new StackoverflowLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<StackoverflowLinkRecord> getRecordType() {
        return StackoverflowLinkRecord.class;
    }

    /**
     * The column <code>STACKOVERFLOW_LINK.LINK_ID</code>.
     */
    public final TableField<StackoverflowLinkRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>STACKOVERFLOW_LINK.ANSWER_COUNT</code>.
     */
    public final TableField<StackoverflowLinkRecord, Integer> ANSWER_COUNT = createField(DSL.name("ANSWER_COUNT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>STACKOVERFLOW_LINK.UPDATED_AT</code>.
     */
    public final TableField<StackoverflowLinkRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private StackoverflowLink(Name alias, Table<StackoverflowLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private StackoverflowLink(Name alias, Table<StackoverflowLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STACKOVERFLOW_LINK</code> table reference
     */
    public StackoverflowLink(String alias) {
        this(DSL.name(alias), STACKOVERFLOW_LINK);
    }

    /**
     * Create an aliased <code>STACKOVERFLOW_LINK</code> table reference
     */
    public StackoverflowLink(Name alias) {
        this(alias, STACKOVERFLOW_LINK);
    }

    /**
     * Create a <code>STACKOVERFLOW_LINK</code> table reference
     */
    public StackoverflowLink() {
        this(DSL.name("STACKOVERFLOW_LINK"), null);
    }

    public <O extends Record> StackoverflowLink(Table<O> child, ForeignKey<O, StackoverflowLinkRecord> key) {
        super(child, key, STACKOVERFLOW_LINK);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<ForeignKey<StackoverflowLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_9);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_9);

        return _link;
    }

    @Override
    @NotNull
    public StackoverflowLink as(String alias) {
        return new StackoverflowLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public StackoverflowLink as(Name alias) {
        return new StackoverflowLink(alias, this);
    }

    @Override
    @NotNull
    public StackoverflowLink as(Table<?> alias) {
        return new StackoverflowLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowLink rename(String name) {
        return new StackoverflowLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowLink rename(Name name) {
        return new StackoverflowLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowLink rename(Table<?> name) {
        return new StackoverflowLink(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Integer, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
