/*
 * This file is generated by jOOQ.
 */
package io.github.pvkvetkin.scrapper.domain.jooq;


import io.github.pvkvetkin.scrapper.domain.jooq.tables.Chat;
import io.github.pvkvetkin.scrapper.domain.jooq.tables.GithubLink;
import io.github.pvkvetkin.scrapper.domain.jooq.tables.Link;
import io.github.pvkvetkin.scrapper.domain.jooq.tables.LinkChat;
import io.github.pvkvetkin.scrapper.domain.jooq.tables.StackoverflowLink;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>GITHUB_LINK</code>.
     */
    public static final GithubLink GITHUB_LINK = GithubLink.GITHUB_LINK;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>LINK_CHAT</code>.
     */
    public static final LinkChat LINK_CHAT = LinkChat.LINK_CHAT;

    /**
     * The table <code>STACKOVERFLOW_LINK</code>.
     */
    public static final StackoverflowLink STACKOVERFLOW_LINK = StackoverflowLink.STACKOVERFLOW_LINK;
}
