name: Bot CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'

env:
  REGISTRY: 'ghcr.io'
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: 'bot-app:latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl bot -am
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }} . -f bot/Dockerfile
      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
