name: Scrapper CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'scrapper/**'
      - '.github/workflows/scrapper.yml'

env:
  REGISTRY: 'ghcr.io'
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: 'scrapper-app:latest'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn checkstyle:check -pl scrapper -am
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl scrapper -am
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }} . -f scrapper/Dockerfile
      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp scrapper/docker-compose.yml ../build
          mkdir ../build/migrations
          cp scrapper/migrations/* ../build/migrations
      - name: Copying migrations and compose file to the remote machine
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: ../build
          remote: /root/scrapper/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          privateKey: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd scrapper
            docker-compose stop scrapper-app
            docker rm scrapper-app
            POSTGRES_HOST=${{ secrets.HOST }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} docker-compose up -d
            docker ps -a
