name: Scrapper CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'scrapper/**'
      - '.github/workflows/scrapper.yml'

env:
  REGISTRY: 'ghcr.io'
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: 'scrapper-app:latest'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn checkstyle:check -pl scrapper -am
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn package -pl scrapper -am
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }} . -f scrapper/Dockerfile
      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copying migrations and docker-compose to the remote machine
        run: |
          echo "${{ secrets.SSHKEY }}" > key.pem

          scp -i key.pem scrapper/migrations/* ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST }}:/root/scrapper/migrations/

          scp -i key.pem scrapper/docker-compose.yml ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST }}:/root/scrapper
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd scrapper
            docker-compose stop scrapper-app
            docker rm scrapper-app
            POSTGRES_HOST=${{ secrets.HOST }} docker-compose up -d
            docker ps -a
